### ISSUE TITLE
authentication fails

### ISSUE THREAD

**Issue by abugher-at-nvidia** [mingbowan/mod-auth-pam#1]
I have installed simplepam with 'pip install simplepam'.

I have a contact defined for my PAM user.  (abugher)  I have turned log_level up to DEBUG for the broker.

When I switched to auth-htpasswd and created a dedicated user, login for that user through webui works.  I see success and failure logged in brokerd.log.

Using auth-pam, when I enter my PAM credentials, I always receive the message "Warning! Invalid user or Password" on the web interface.  brokerd.log shows no success or failure messages.  /var/log/secure also shows no new messages around the time of login failure, suggesting to me that the credentials never made it all the way to PAM.

I see these (trimmed) messages in brokerd.log during shinken startup, relating to auth-pam:

> WARNING: [broker-master] Cannot import auth-pam..module : No module named simplepam
> WARNING: [broker-master] Trying to load '/var/lib/shinken/modules/auth-pam' as an (very-)old-style shinken "module"
> ERROR: [broker-master] Could not import bare 'module.py' from /var/lib/shinken/modules/auth-pam : No module named simplepam
>   File "/var/lib/shinken/modules/auth-pam/module.py", line 5, in <module>
>     from simplepam import authenticate
> ImportError: No module named simplepam
> INFO: [broker-master] Instantiate an Apache/Passwd UI module for plugin auth-pam
> ERROR: [broker-master] The module auth-pam raised an exception 'Module' object has no attribute 'passwd', I remove it! traceback=Traceback (most recent call last):
>   File "/usr/lib/python2.6/site-packages/shinken/modulesmanager.py", line 234, in get_instances
>     inst = module.get_instance(mod_conf)
>   File "/var/lib/shinken/modules/auth-htpasswd/module.py", line 52, in get_instance
>     instance = Passwd_Webui(plugin)
>   File "/var/lib/shinken/modules/auth-htpasswd/module.py", line 59, in **init**
>     self.passwd = modconf.passwd
> AttributeError: 'Module' object has no attribute 'passwd'

Please let me know of any further information I can provide, full logs, config files, etc.

**Comment by mingbowan** [comment]
the error shows simplepam is not installed correctly. If you're using virtualenv, make sure your shinken user uses the same virtualenv. if not, try pip install using root or shinken user. 
you can verify by switching to shinken user and try "import simplepam" in python cli

**Comment by abugher-at-nvidia** [comment]
Thank you.  Here's how that went:

> abugher@shinken( ~ )$ sudo pip uninstall simplepam
> Uninstalling simplepam:
>   /usr/lib/python2.6/site-packages/simplepam-0.1.5-py2.6.egg-info
>   /usr/lib/python2.6/site-packages/simplepam.py
>   /usr/lib/python2.6/site-packages/simplepam.pyc
> Proceed (y/n)? y
>   Successfully uninstalled simplepam
> abugher@shinken( ~ )$ sudo pip install simplepam
> Downloading/unpacking simplepam
>   Downloading simplepam-0.1.5.tar.gz
>   Running setup.py egg_info for package simplepam
> Installing collected packages: simplepam
>   Running setup.py install for simplepam
> Successfully installed simplepam
> Cleaning up...
> abugher@shinken( ~ )$ sudo su - shinken
> [shinken@shinken ~]$ python
> Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import simplepam
> > > > Traceback (most recent call last):
> > > >   File "<stdin>", line 1, in <module>
> > > > ImportError: No module named simplepam

I'm pretty weak on Python.  Does this indicate a problem in simplepam?

I found this forum thread with a similar issue which allegedly went away after "some modules reinstall":  http://forum.shinken-monitoring.org/threads/1177

**Comment by abugher-at-nvidia** [comment]
The simplepam files ( /usr/lib/python2.6/site-packages/simplepam\* ) were owned by root and unreadable by world, making them unavailable to user shinken.  For the moment, I changed the permissions of the files to be world-readable.

Now user shinken can import simplepam.  brokerd.log has nothing to say about auth-pam except "correctly loaded".  Everything looks good, except that I still cannot log in.  I don't see any failure message in the log.

That may or may not be the SAME problem, though.  I'm going to educate myself on the term "virtualenv" and sniff around a little more.  Thank you much for your quick response!

**Comment by mingbowan** [comment]
do you have pam config for service shinken? you can simply do 
ln -s /etc/pam.d/system-auth /etc/pam.d/shinken

or
change "service_name" in auth_pam.cfg to "system-auth"  and try again

**Comment by abugher-at-nvidia** [comment]
I created the symlink.  PAM login works!  A patient coworker is explaining to me why that fixed things.  Thank you very much.
